---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: {{ .Values.namespace }}
data:
  conf.yml: |
    ---
    # Page meta info, like heading, footer text and nav links
    pageInfo:
      title: Dashy
      description: Welcome to your new dashboard!
      navLinks:
      - title: GitHub
        path: https://github.com/Lissy93/dashy
      - title: Documentation
        path: https://dashy.to/docs

    # Optional app settings and configuration
    appConfig:
      theme: colorful

    # Main content - An array of sections, each containing an array of items
    sections:
    - name: Getting Started
      icon: fas fa-rocket
      items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
      - title: GitHub
        description: Source Code, Issues and Pull Requests
        url: https://github.com/lissy93/dashy
        icon: favicon
      - title: Docs
        description: Configuring & Usage Documentation
        provider: Dashy.to
        icon: far fa-book
        url: https://dashy.to/docs
      - title: Showcase
        description: See how others are using Dashy
        url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
        icon: far fa-grin-hearts
      - title: Config Guide
        description: See full list of configuration options
        url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
        icon: fas fa-wrench
      - title: Support
        description: Get help with Dashy, raise a bug, or get in contact
        url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
        icon: far fa-hands-helping
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.config.prometheusNamespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
      - targets: ['localhost:9090']
    - job_name: kubernetes-cadvisor
      scrape_interval: 10s
      scrape_timeout: 10s
      metrics_path: /metrics/cadvisor
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    - job_name: "kubernetes-pods"
      kubernetes_sd_configs:
        - role: pod