{{ if .Values.config.enablePihole }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.piholePVCDNSMasq }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.piholeStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.piholePVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.piholeStorage }}
{{ end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.postgresMinifluxPVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.postgresMinifluxStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.qbittorrentPVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.qbittorrentStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.mediaPVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb
  resources:
    requests:
      storage: {{ .Values.config.mediaStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.dashyPVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.dashyStorage }}