{{ if .Values.config.enablePihole }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.piholePVCDNSMasq }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.piholeStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.piholePVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.piholeStorage }}
{{ end }}
{{ if .Values.config.enableMiniflux }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.postgresMinifluxPVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.postgresMinifluxStorage }}
{{ end }}
{{ if .Values.config.enableQbittorrent }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.qbittorrentPVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.qbittorrentStorage }}
{{ end }}
{{ if .Values.config.enableJellyfin }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.mediaPVC }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  volumeName: {{ .Values.config.mediaVolume }}
  resources:
    requests:
      storage: {{ .Values.config.mediaStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.jellyfinPVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.jellyfinStorage }}
{{ end }}
{{ if .Values.config.enablePrometheus }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.prometheusPVC }}
  namespace: {{ .Values.config.prometheusNamespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb
  resources:
    requests:
      storage: {{ .Values.config.prometheusStorage }}
{{ end }}
{{ if .Values.config.enableGrafana }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.grafanaPVC }}
  namespace: {{ .Values.config.prometheusNamespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.grafanaStorage }}
{{ end }}
{{ if .Values.config.enableFlame }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.config.flamePVC }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.config.flameStorage }}
{{ end }}