{{ if .Values.config.enablePihole }}
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secrets
  namespace: {{ .Values.namespace }}
stringData:
  WEBPASSWORD: {{ .Values.config.piholeWebPassword }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-miniflux-secrets
  namespace: {{ .Values.namespace }}
stringData:
  POSTGRESQL_PASSWORD: {{ .Values.config.postgresMinifluxPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: miniflux-secrets
  namespace: {{ .Values.namespace }}
stringData:
  DATABASE_URL: "postgres://miniflux:{{ .Values.config.postgresMinifluxPassword }}@postgres-miniflux-svc/miniflux?sslmode=disable"
  ADMIN_USERNAME: {{ .Values.config.minifluxAdmin }}
  ADMIN_PASSWORD: {{ .Values.config.minifluxAdminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-cloudflare-secrets
  namespace: kube-system
stringData:
  email: {{ .Values.config.traefikEmail }}
  apikey: "{{ .Values.config.traefikAPIKey}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: default
stringData:
  username: {{ .Values.config.sambaUsername }}
  password: "{{ .Values.config.sambaPassword}}"
