{{ if .Values.config.enablePihole }}
apiVersion: v1
kind: Service
metadata:
  name: pihole-svc
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - port: {{ .Values.config.piholeDNSPort }}
      name: dns-udp
      protocol: UDP
      targetPort: 53
    - port: {{ .Values.config.piholeDNSPort }}
      name: dns-tcp
      protocol: TCP
      targetPort: 53
    - port: {{ .Values.config.piholeAdminPort }}
      name: web
      protocol: TCP
      targetPort: 80
{{ end }}
{{ if .Values.config.enableMiniflux }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-miniflux-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: postgres-miniflux
  ports:
    - port: 5432
      name: postgres
      protocol: TCP
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: miniflux
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
{{ end }}
{{ if .Values.config.enableExcalidraw }}
---
apiVersion: v1
kind: Service
metadata:
  name: excalidraw-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: excalidraw
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
{{ end }}
{{ if .Values.config.enableQbittorrent }}
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 6881
      name: torrent-tcp
      protocol: TCP
      targetPort: 6881
    - port: 6881
      name: torrent-udp
      protocol: UDP
      targetPort: 6881
{{ end }}
{{ if .Values.config.enableJellyfin }}
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: jellyfin
  ports:
    - port: 8096
      name: http
      protocol: TCP
      targetPort: 8096
{{ end }}
{{ if .Values.config.enablePrometheus }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: {{ .Values.config.prometheusNamespace }}
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - port: 9090
      name: http
      protocol: TCP
      targetPort: 9090
{{ end }}
{{ if .Values.config.enableGrafana }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: {{ .Values.config.prometheusNamespace }}
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - port: 3000
      name: http
      protocol: TCP
      targetPort: 3000
{{ end }}
{{ if .Values.config.enableFlame }}
---
apiVersion: v1
kind: Service
metadata:
  name: flame-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: flame
  ports:
    - port: 5005
      name: http
      protocol: TCP
      targetPort: 5005
{{ end }}